### ISSUE TITLE
Create diagram with just tables and relationships, not displaying any columns.

### ISSUE THREAD

**Issue by adriens** [adriens/schemacrawler-plugin-neo4j#10]
As requested on https://github.com/sualeh/SchemaCrawler/issues/141 

> create diagram with just tables and relationships, not displaying any columns.

**Comment by adriens** [comment]
take a look at  ```CYPHER_QUERIES.md``` on top of the project, at the end you get the following graph :


![relations-between-tables-2](https://user-images.githubusercontent.com/5235127/32086715-c41821f4-bb22-11e7-8fb2-be50aca1368a.jpg)

**Comment by schemacrawler** [comment]
Awesome! Thanks!
