### ISSUE TITLE
Register adriens.nc domain

### ISSUE THREAD

**Issue by schemacrawler** [adriens/schemacrawler-plugin-neo4j#6]
Register adriens.nc domain, so you can have http://schemacrawler-plugin-neo4j.adriens.nc point to this GitHub project.

**Comment by adriens** [comment]
Yep, sonatype just sent me an update about that ;-p
i"ve just created http://adriens.github.io/
.. with github pages so it has responsive design features on mobile devices. I'll use the wizard to maintain this site.It should do the job.
For now, the content is a bit dummy, but i'll complete it as soons as possible.
Thanks for advice. I'll send you an email about what i've learned about gthub platform these days and why you really should join me on it. It's really amazing !
